import { ReactNode } from 'react'
import './globals.css'
import { Footer, Navbar } from '@/components'

export const metadata = {
  title: 'car show',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  )
}
